# Generated by Django 4.0.8 on 2022-10-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='buddy', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('building_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('kerala', 'KERALA'), ('tamil_nadu', 'TAMIL NADU'), ('karnadaka', 'KARNADAKA')], default='kerala', max_length=20)),
                ('pincode', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('alt_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer_percentage', models.CharField(default=0, max_length=100)),
                ('image', models.ImageField(upload_to='Category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(default='amal', max_length=100)),
                ('discount_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('coupon_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='cropped_images/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image_1', models.ImageField(upload_to='image_2_of_products')),
                ('image_2', models.ImageField(upload_to='image_2_of_products')),
                ('image_3', models.ImageField(upload_to='image_3_of_products')),
                ('image_4', models.ImageField(upload_to='image_4_of_products')),
                ('arrival_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('mrp', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=300)),
                ('stock_available', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('total_sold', models.IntegerField()),
                ('is_trusted', models.CharField(choices=[('trusted', 'Trusted'), ('not_trusted', 'Not Trusted')], default='trusted', max_length=20)),
                ('available_status', models.CharField(choices=[('availabe', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('offer_percentage', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('refered_user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(default='buddy', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('signup_day', models.CharField(default=27, max_length=50)),
                ('signup_month', models.CharField(default=10, max_length=50)),
                ('signup_year', models.CharField(default=2022, max_length=50)),
                ('active_status', models.CharField(default='active', max_length=50)),
                ('is_admin', models.CharField(default='false', max_length=50)),
                ('profile_image', models.ImageField(upload_to='profile_image/')),
                ('reference_id', models.CharField(default='0000000000', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widecity_shopping.category')),
            ],
        ),
        migrations.CreateModel(
            name='Return_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widecity_shopping.users')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_day', models.CharField(default=27, max_length=100)),
                ('Order_month', models.CharField(default=10, max_length=100)),
                ('Order_year', models.CharField(default=2022, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(default='ordered', max_length=100)),
                ('Address', models.CharField(default=1, max_length=20)),
                ('payment_method', models.CharField(default='cod', max_length=20)),
                ('total_price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widecity_shopping.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widecity_shopping.users')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.CharField(default=0, max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widecity_shopping.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widecity_shopping.users')),
            ],
        ),
    ]
