# Generated by Django 4.0.8 on 2022-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='mrp',
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.CharField(default=28, max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='offer_percentage',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_day',
            field=models.CharField(default=28, max_length=50),
        ),
    ]
