# Generated by Django 4.0.8 on 2022-10-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0004_category_offer_percentage_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_percentage',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
