# Generated by Django 4.0.8 on 2022-10-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0005_products_offer_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(default='amal', max_length=100)),
                ('discount_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.CharField(default=19, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_day',
            field=models.CharField(default=19, max_length=50),
        ),
    ]
