# Generated by Django 4.0.8 on 2022-10-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0006_coupon_alter_orders_order_day_alter_users_signup_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('coupon_code', models.CharField(max_length=100)),
            ],
        ),
    ]
