# Generated by Django 4.0.8 on 2022-10-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0007_coupon_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon_history',
            old_name='user',
            new_name='user_id',
        ),
    ]
