# Generated by Django 4.0.8 on 2022-10-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0009_alter_orders_order_day_alter_users_signup_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reference_id',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.CharField(default=21, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_day',
            field=models.CharField(default=21, max_length=50),
        ),
    ]
