# Generated by Django 4.0.8 on 2022-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0011_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active_status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
